# Usando a imagem base oficial do Python
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o código da aplicação para dentro do contêiner
COPY . /app

# Instalar as dependências necessárias
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta 5000 (usada pela aplicação Flask)
EXPOSE 5000

# Comando para rodar a aplicação Flask
CMD ["python", "app.py"]